services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=migration_db'
      - 'POSTGRES_PASSWORD=migration_db_secret'
      - 'POSTGRES_USER=migration_db_user'
    ports:
      - '5432:5432'
