server:
  port: 0
spring:
  profiles:
    default: quartz
  sql:
    init:
      data-locations:
        - classpath:db/ddl/quartz-postgresql.sql
        - classpath:db/ddl/shedlock-postgresql.sql
        - classpath:db/ddl/task.sql
      enabled: true
      mode: ALWAYS
      continue-on-error: false
      platform: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/migration_db
    username: migration_db_user
    password: migration_db_secret
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
app-generic:
  simulate-slow-operation: true
  minInSeconds: 15
  maxInSeconds: 45